name: GDRemake
options:
  bundleIdPrefix: com.allowq
  deploymentTarget:
    iOS: "14.0"
targets:
  GDRemake:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
        buildPhase: resources
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: GD Remake
        UILaunchScreen: {}
        UIStatusBarHidden: true
        UIViewControllerBasedStatusBarAppearance: false
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
